package com.integrador.ReservaCitas.util;

public class SQLQueries {
    public static final String CREATETABLES_ODONTOLOGO =
            "DROP TABLE IF EXISTS ODONTOLOGOS;" +
                    "CREATE TABLE ODONTOLOGOS(MATRICULA VARCHAR(255) PRIMARY KEY, NOMBRE VARCHAR(255), APELLIDO VARCHAR(255));" ;
    public static final String INSERTCUSTOM_ODONTOLOGO = "INSERT INTO ODONTOLOGOS VALUES(?,?,?);";
    public static final String UPDATECUSTOM_ODONTOLOGO = "UPDATE ODONTOLOGOS SET NOMBRE=? WHERE MATRICULA=?";

    public static final String SELECT_ODONTOLOGO = "SELECT * FROM ODONTOLOGOS WHERE MATRICULA=?";

    public static final String SELECTALL_ODONTOLOGOS = "SELECT * FROM ODONTOLOGOS";

    public static final String DELETE_ODONTOLOGO = "DELETE FROM ODONTOLOGOS WHERE MATRICULA=?";

    public static final String CREATETABLES_PACIENTE =
            "DROP TABLE IF EXISTS PACIENTES;" +
                    "CREATE TABLE PACIENTES(DNI VARCHAR(255) PRIMARY KEY, NOMBRE VARCHAR(255), APELLIDO VARCHAR(255), FECHA_ALTA DATE, DOMICILIO_ID INT);" ;
    public static final String INSERTCUSTOM_PACIENTE = "INSERT INTO PACIENTES VALUES(?,?,?,?,?);";
    public static final String UPDATECUSTOM_PACIENTE = "UPDATE PACIENTES SET NOMBRE=? WHERE DNI=?";

    public static final String SELECT_PACIENTE = "SELECT * FROM PACIENTES WHERE DNI=?";

    public static final String SELECTALL_PACIENTES = "SELECT * FROM PACIENTES";

    public static final String DELETE_PACIENTE = "DELETE FROM PACIENTES WHERE DNI=?";

    public static final String CREATETABLES_DOMICILIO =
            "DROP TABLE IF EXISTS DOMICILIO;" +
                    "CREATE TABLE DOMICILIO(ID INT AUTO_INCREMENT PRIMARY KEY, CALLE VARCHAR(255), NUMERO VARCHAR(255), LOCALIDAD VARCHAR(255), PROVINCIA VARCHAR(255));" ;
    public static final String INSERTCUSTOM_DOMICILIO = "INSERT INTO DOMICILIO (CALLE, NUMERO, LOCALIDAD, PROVINCIA) VALUES(?,?,?,?);";
    public static final String SELECT_DOMICILIO = "SELECT ID, CALLE, NUMERO, LOCALIDAD, PROVINCIA FROM DOMICILIO WHERE ID=?";
}
